import { StrategyDefinition } from './strategy.interface';

export const BREAKOUT_STRATEGIES: StrategyDefinition[] = [
  {
    name: 'BB_BREAKOUT',
    displayName: 'Bollinger Breakout',
    description: 'Bollinger Band squeeze followed by explosive breakout. Waits for consolidation then rides the expansion.',
    category: 'BREAKOUT',
    tier: 'SILVER',
    assetClasses: ['CRYPTO', 'FOREX', 'STOCK'],
    bestTimeframes: ['1h', '4h'],
    indicatorWeights: [
      { indicator: 'Bollinger Bands', weight: 2.0, required: true },
      { indicator: 'Volume', weight: 2.0, required: true },
      { indicator: 'MACD', weight: 1.2 },
      { indicator: 'RSI(14)', weight: 0.8 },
    ],
    riskParams: { atrMultiplierSL: 1.5, atrMultiplierTP: 3.0, minRR: 2.0 },
    entryLogic: 'BB bandwidth contracts to 6-month low (squeeze). Enter breakout candle on close outside band with 2× average volume.',
    exitLogic: 'Target at 2× BB width from breakout point. Stop at band midline.',
    tags: ['squeeze', 'volatility-breakout', 'volume'],
  },
  {
    name: 'VOLUME_BREAKOUT',
    displayName: 'Volume Surge Breakout',
    description: 'Breakout of consolidation range confirmed by unusually high volume (3× 20-bar average).',
    category: 'BREAKOUT',
    tier: 'GOLD',
    assetClasses: ['CRYPTO', 'STOCK'],
    bestTimeframes: ['1h', '4h', '1d'],
    indicatorWeights: [
      { indicator: 'Volume', weight: 3.0, required: true },
      { indicator: 'OBV', weight: 1.5 },
      { indicator: 'MACD', weight: 1.2 },
      { indicator: 'Bollinger Bands', weight: 1.0 },
    ],
    riskParams: { atrMultiplierSL: 1.5, atrMultiplierTP: 4.0, minRR: 2.5, positionSizeFraction: 0.06 },
    signalThreshold: 0.30,
    entryLogic: 'Price breaks key high/low on volume ≥ 3× 20-bar average. OBV must confirm (trending up for BUY, down for SELL).',
    exitLogic: 'Trail stop by 1×ATR as trade develops. Target at next key resistance/support.',
    tags: ['volume', 'institutional', 'breakout'],
  },
  {
    name: 'ATR_CHANNEL_BREAK',
    displayName: 'ATR Channel Breakout',
    description: 'Donchian-style channel breakout with ATR-based dynamic bands. Captures trending moves early.',
    category: 'BREAKOUT',
    tier: 'GOLD',
    assetClasses: ['FOREX', 'CRYPTO', 'COMMODITY'],
    bestTimeframes: ['4h', '1d'],
    indicatorWeights: [
      { indicator: 'ATR Channel', weight: 2.5, required: true },
      { indicator: 'ADX', weight: 2.0, required: true },
      { indicator: 'EMA(50)', weight: 1.0 },
      { indicator: 'Volume', weight: 1.0 },
    ],
    riskParams: { atrMultiplierSL: 2.0, atrMultiplierTP: 4.0, minRR: 2.0, positionSizeFraction: 0.05 },
    signalThreshold: 0.30,
    entryLogic: 'Price closes beyond 20-period high/low + 2×ATR. ADX must be rising above 20. Enter on breakout close.',
    exitLogic: 'Trailing stop at prior 10-period extreme. Maximum hold time: 5 candles.',
    tags: ['donchian', 'atr', 'trend-breakout'],
  },
  {
    name: 'PIVOT_BREAKOUT',
    displayName: 'Pivot Point Breakout',
    description: 'Breakout above/below classic weekly/monthly pivot levels (PP, R1-R3, S1-S3) with momentum.',
    category: 'BREAKOUT',
    tier: 'GOLD',
    assetClasses: ['FOREX', 'STOCK', 'CRYPTO'],
    bestTimeframes: ['1h', '4h'],
    indicatorWeights: [
      { indicator: 'Pivot Points', weight: 2.5, required: true },
      { indicator: 'MACD', weight: 1.5 },
      { indicator: 'Volume', weight: 1.5 },
      { indicator: 'RSI(14)', weight: 0.8 },
    ],
    riskParams: { atrMultiplierSL: 1.2, atrMultiplierTP: 2.5, minRR: 2.0 },
    entryLogic: 'Price breaks and holds above R1/R2/R3 (BUY) or below S1/S2/S3 (SELL) with MACD momentum and elevated volume.',
    exitLogic: 'Target at next pivot level. Stop at current pivot if broken.',
    tags: ['pivot', 'key-levels', 'institutional'],
  },
];
