import { StrategyDefinition } from './strategy.interface';

export const COMPOSITE_STRATEGIES: StrategyDefinition[] = [
  {
    name: 'MARKET_STRUCTURE',
    displayName: 'Market Structure (BOS/CHoCH)',
    description: 'Identifies Break of Structure (BOS) and Change of Character (CHoCH) for high-probability trend continuation and reversal entries.',
    category: 'COMPOSITE',
    tier: 'GOLD',
    assetClasses: ['CRYPTO', 'FOREX', 'STOCK'],
    bestTimeframes: ['1h', '4h', '1d'],
    indicatorWeights: [
      { indicator: 'Market Structure', weight: 3.0, required: true },
      { indicator: 'Volume', weight: 1.5 },
      { indicator: 'RSI(14)', weight: 1.0 },
      { indicator: 'EMA(50)', weight: 1.0 },
    ],
    riskParams: { atrMultiplierSL: 1.5, atrMultiplierTP: 3.0, minRR: 2.0, positionSizeFraction: 0.06 },
    signalThreshold: 0.35,
    entryLogic: 'BOS: price breaks prior swing high/low confirming trend continuation — enter on retest. CHoCH: first break against trend structure — signals potential reversal.',
    exitLogic: 'Target next structural high/low. Stop at last structural point (swing low for BUY, swing high for SELL).',
    tags: ['smart-money', 'structure', 'swing'],
  },
  {
    name: 'SMC_ICT',
    displayName: 'Smart Money Concepts (ICT)',
    description: 'Institutional Candle Trader concepts: Order Blocks, Fair Value Gaps, Liquidity Pools, Kill Zones. For experienced traders only.',
    category: 'COMPOSITE',
    tier: 'PLATINUM',
    assetClasses: ['FOREX', 'CRYPTO', 'STOCK'],
    bestTimeframes: ['15m', '1h', '4h'],
    indicatorWeights: [
      { indicator: 'Order Blocks', weight: 3.5, required: true },
      { indicator: 'Fair Value Gap', weight: 2.5 },
      { indicator: 'Liquidity Sweep', weight: 2.0 },
      { indicator: 'Market Structure', weight: 2.0 },
      { indicator: 'Volume', weight: 1.5 },
      { indicator: 'VWAP', weight: 1.0 },
    ],
    riskParams: { atrMultiplierSL: 1.0, atrMultiplierTP: 3.0, minRR: 3.0, positionSizeFraction: 0.05 },
    signalThreshold: 0.40,
    requiresFundamental: false,
    fundamentalWeight: 0.10,
    entryLogic: 'Price sweeps liquidity (stop hunt) above/below swing, then returns to Order Block or Fair Value Gap. Enter at OB mitigation with lower-timeframe confirmation.',
    exitLogic: 'Target at opposing liquidity pool or next order block. Stop behind liquidity wick.',
    tags: ['ict', 'smart-money', 'order-block', 'platinum'],
  },
  {
    name: 'WYCKOFF_CYCLE',
    displayName: 'Wyckoff Method',
    description: 'Identifies Wyckoff accumulation (spring/upthrust) and distribution cycles using volume-spread analysis.',
    category: 'COMPOSITE',
    tier: 'PLATINUM',
    assetClasses: ['CRYPTO', 'STOCK', 'COMMODITY'],
    bestTimeframes: ['4h', '1d'],
    indicatorWeights: [
      { indicator: 'Wyckoff Phase', weight: 3.5, required: true },
      { indicator: 'Volume', weight: 3.0, required: true },
      { indicator: 'OBV', weight: 2.0 },
      { indicator: 'RSI(14)', weight: 1.0 },
      { indicator: 'Bollinger Bands', weight: 0.8 },
    ],
    riskParams: { atrMultiplierSL: 2.0, atrMultiplierTP: 5.0, minRR: 2.5, positionSizeFraction: 0.08 },
    signalThreshold: 0.35,
    requiresFundamental: true,
    fundamentalWeight: 0.25,
    entryLogic: 'Accumulation: Spring (false breakdown below support with low volume) confirmed by Volume Spread Analysis. Distribution: Upthrust (false breakout above resistance on low volume).',
    exitLogic: 'Accumulation targets: Phase D markup (SOS). Distribution targets: Phase D markdown.',
    tags: ['wyckoff', 'vsa', 'institutional', 'platinum', 'long-term'],
  },
  {
    name: 'FULL_STACK_MTF',
    displayName: 'Full Stack Multi-Timeframe',
    description: 'Complete multi-timeframe analysis requiring alignment across W/D/4H/1H. Highest accuracy, lowest frequency. Platinum exclusive.',
    category: 'COMPOSITE',
    tier: 'PLATINUM',
    assetClasses: ['CRYPTO', 'FOREX', 'STOCK', 'COMMODITY'],
    bestTimeframes: ['1h', '4h'],
    indicatorWeights: [
      { indicator: 'HTF Trend Alignment', weight: 3.0, required: true },
      { indicator: 'Market Structure', weight: 2.5, required: true },
      { indicator: 'EMA(50)', weight: 2.0 },
      { indicator: 'RSI(14)', weight: 1.5 },
      { indicator: 'MACD', weight: 1.5 },
      { indicator: 'ADX', weight: 1.5 },
      { indicator: 'Volume', weight: 1.5 },
      { indicator: 'Fibonacci', weight: 1.5 },
    ],
    riskParams: { atrMultiplierSL: 2.0, atrMultiplierTP: 6.0, minRR: 3.0, positionSizeFraction: 0.07 },
    signalThreshold: 0.45,
    requiresFundamental: true,
    fundamentalWeight: 0.30,
    entryLogic: 'Weekly + Daily + 4H must all align in same direction. 1H provides entry trigger. All major indicators must agree. Minimum 6 confirming factors.',
    exitLogic: 'Scale out: 50% at 3:1 R/R, remainder with trailing stop. Maximum drawdown 2×ATR from entry.',
    tags: ['multi-timeframe', 'all-confluence', 'highest-accuracy', 'platinum'],
  },
  {
    name: 'INSTITUTIONAL_FLOW',
    displayName: 'Institutional Flow',
    description: 'Tracks institutional order flow via volume profile, delta divergence, and OBV trend to trade with smart money.',
    category: 'COMPOSITE',
    tier: 'PLATINUM',
    assetClasses: ['CRYPTO', 'STOCK'],
    bestTimeframes: ['1h', '4h'],
    indicatorWeights: [
      { indicator: 'Volume Profile', weight: 3.0, required: true },
      { indicator: 'OBV', weight: 2.5, required: true },
      { indicator: 'VWAP', weight: 2.0 },
      { indicator: 'Volume', weight: 2.0 },
      { indicator: 'RSI(14)', weight: 1.0 },
      { indicator: 'Market Structure', weight: 1.5 },
    ],
    riskParams: { atrMultiplierSL: 1.5, atrMultiplierTP: 4.0, minRR: 2.5, positionSizeFraction: 0.06 },
    signalThreshold: 0.40,
    requiresFundamental: true,
    fundamentalWeight: 0.20,
    entryLogic: 'High Volume Node (HVN) acts as support/resistance. OBV diverges from price (accumulation/distribution). Enter at low-volume node rejection.',
    exitLogic: 'Target at next HVN. Stop at volume gap below current HVN.',
    tags: ['volume-profile', 'institutional', 'obv', 'platinum'],
  },
];
