import { StrategyDefinition } from './strategy.interface';

export const REVERSAL_STRATEGIES: StrategyDefinition[] = [
  {
    name: 'RSI_DIVERGENCE',
    displayName: 'RSI Divergence',
    description: 'Detects bullish/bearish divergence between RSI and price. High-accuracy reversal signal at extremes.',
    category: 'REVERSAL',
    tier: 'SILVER',
    assetClasses: ['CRYPTO', 'FOREX', 'STOCK', 'COMMODITY'],
    bestTimeframes: ['1h', '4h', '1d'],
    indicatorWeights: [
      { indicator: 'RSI(14)', weight: 2.5, required: true },
      { indicator: 'StochRSI', weight: 1.5 },
      { indicator: 'MACD', weight: 1.0 },
      { indicator: 'Bollinger Bands', weight: 0.8 },
    ],
    riskParams: { atrMultiplierSL: 1.5, atrMultiplierTP: 2.5, minRR: 1.5 },
    signalThreshold: 0.30,
    entryLogic: 'Price makes lower low while RSI makes higher low (bullish divergence), or price higher high with RSI lower high (bearish). Enter at divergence confirmation candle close.',
    exitLogic: 'Target at previous swing high/low or 2.5×ATR. Stop below/above divergence low/high.',
    tags: ['divergence', 'counter-trend', 'rsi'],
  },
  {
    name: 'STOCH_REVERSAL',
    displayName: 'Stochastic Reversal',
    description: 'StochRSI oversold/overbought cross with RSI confirmation for mean reversion trades.',
    category: 'REVERSAL',
    tier: 'SILVER',
    assetClasses: ['CRYPTO', 'FOREX', 'COMMODITY'],
    bestTimeframes: ['15m', '1h', '4h'],
    indicatorWeights: [
      { indicator: 'StochRSI', weight: 2.0, required: true },
      { indicator: 'RSI(14)', weight: 1.5 },
      { indicator: 'Williams %R', weight: 1.2 },
      { indicator: 'Bollinger Bands', weight: 0.8 },
    ],
    riskParams: { atrMultiplierSL: 1.2, atrMultiplierTP: 2.0, minRR: 1.5 },
    entryLogic: 'StochRSI %K crosses above %D from below 20 (BUY) or crosses below from above 80 (SELL). RSI confirms with <40 or >60.',
    exitLogic: 'StochRSI reaches 50 midpoint or price hits 2×ATR profit target.',
    tags: ['mean-reversion', 'oscillator', 'short-term'],
  },
  {
    name: 'BB_MEAN_REVERSION',
    displayName: 'Bollinger Mean Reversion',
    description: 'Trades price rejection from outer Bollinger Bands back toward the 20-period moving average.',
    category: 'REVERSAL',
    tier: 'SILVER',
    assetClasses: ['CRYPTO', 'FOREX', 'STOCK'],
    bestTimeframes: ['1h', '4h'],
    indicatorWeights: [
      { indicator: 'Bollinger Bands', weight: 2.5, required: true },
      { indicator: 'RSI(14)', weight: 1.5, required: true },
      { indicator: 'StochRSI', weight: 1.0 },
      { indicator: 'Volume', weight: 0.8 },
    ],
    riskParams: { atrMultiplierSL: 1.0, atrMultiplierTP: 1.8, minRR: 1.5 },
    entryLogic: 'Price closes outside outer band with RSI at extreme. Enter on next candle that closes inside band (reversion confirmation).',
    exitLogic: 'Target at BB midline (20-SMA). Stop 0.5% beyond outer band.',
    tags: ['mean-reversion', 'squeeze', 'range'],
  },
  {
    name: 'ENGULFING_REVERSAL',
    displayName: 'Engulfing Candle Reversal',
    description: 'Bullish/bearish engulfing candlestick patterns at key support/resistance levels.',
    category: 'REVERSAL',
    tier: 'GOLD',
    assetClasses: ['CRYPTO', 'FOREX', 'STOCK', 'COMMODITY'],
    bestTimeframes: ['4h', '1d'],
    indicatorWeights: [
      { indicator: 'Engulfing Pattern', weight: 3.0, required: true },
      { indicator: 'RSI(14)', weight: 1.2 },
      { indicator: 'Volume', weight: 1.8, required: true },
      { indicator: 'Support/Resistance', weight: 1.5 },
    ],
    riskParams: { atrMultiplierSL: 1.5, atrMultiplierTP: 3.0, minRR: 2.0, positionSizeFraction: 0.06 },
    signalThreshold: 0.35,
    entryLogic: 'Bullish/bearish engulfing candle forms at identified S/R level with 1.5× average volume. RSI must be in reversal zone (<40 or >60).',
    exitLogic: 'Target at next major S/R level. Stop below/above engulfing candle body.',
    tags: ['candlestick', 'key-levels', 'volume-confirmed'],
  },
  {
    name: 'FIBONACCI_REVERSAL',
    displayName: 'Fibonacci Retracement',
    description: 'Price reversal from key Fibonacci levels (38.2%, 50%, 61.8%) with oscillator confirmation.',
    category: 'REVERSAL',
    tier: 'GOLD',
    assetClasses: ['CRYPTO', 'FOREX', 'STOCK', 'COMMODITY'],
    bestTimeframes: ['4h', '1d'],
    indicatorWeights: [
      { indicator: 'Fibonacci', weight: 2.5, required: true },
      { indicator: 'RSI(14)', weight: 1.5 },
      { indicator: 'MACD', weight: 1.2 },
      { indicator: 'Volume', weight: 1.0 },
    ],
    riskParams: { atrMultiplierSL: 1.0, atrMultiplierTP: 2.5, minRR: 2.0 },
    entryLogic: 'Price reaches 38.2%, 50%, or 61.8% Fibonacci retracement of prior swing with RSI reversal and MACD hook.',
    exitLogic: 'Target at 0% (full retracement) or 161.8% extension. Stop below/above fib level by 0.5×ATR.',
    tags: ['fibonacci', 'swing', 'support-resistance'],
  },
];
