import { StrategyDefinition } from './strategy.interface';

export const SCALPING_STRATEGIES: StrategyDefinition[] = [
  {
    name: 'RAPID_RSI_STOCH',
    displayName: 'RSI + Stoch Scalp',
    description: 'Fast oscillator confluence scalp. RSI and StochRSI must both signal in same direction for entry.',
    category: 'SCALPING',
    tier: 'GOLD',
    assetClasses: ['CRYPTO', 'FOREX'],
    bestTimeframes: ['1m', '5m', '15m'],
    indicatorWeights: [
      { indicator: 'RSI(14)', weight: 2.0, required: true },
      { indicator: 'StochRSI', weight: 2.0, required: true },
      { indicator: 'MACD', weight: 1.0 },
      { indicator: 'Bollinger Bands', weight: 0.8 },
    ],
    riskParams: { atrMultiplierSL: 0.8, atrMultiplierTP: 1.5, minRR: 1.5, positionSizeFraction: 0.03 },
    signalThreshold: 0.35,
    entryLogic: 'Both RSI < 30 + StochRSI %K crosses %D from below 20 (BUY), or RSI > 70 + StochRSI from above 80 (SELL).',
    exitLogic: 'Quick 1.5:1 R/R exit. Hard stop at 0.8×ATR. Never hold more than 30 candles.',
    tags: ['scalp', 'fast', 'oscillator-confluence'],
  },
  {
    name: 'EMA_RIBBON',
    displayName: 'EMA Ribbon Scalp',
    description: 'Multi-EMA ribbon (5/8/13/21) all fanning in same direction for high-momentum scalp entries.',
    category: 'SCALPING',
    tier: 'GOLD',
    assetClasses: ['CRYPTO', 'FOREX', 'STOCK'],
    bestTimeframes: ['5m', '15m', '1h'],
    indicatorWeights: [
      { indicator: 'EMA(5)', weight: 1.5, required: true },
      { indicator: 'EMA(8)', weight: 1.5, required: true },
      { indicator: 'EMA(13)', weight: 1.5 },
      { indicator: 'EMA(21)', weight: 1.5 },
      { indicator: 'Volume', weight: 1.2 },
      { indicator: 'RSI(14)', weight: 0.5 },
    ],
    riskParams: { atrMultiplierSL: 0.8, atrMultiplierTP: 1.6, minRR: 1.5, positionSizeFraction: 0.03 },
    signalThreshold: 0.40,
    entryLogic: 'All ribbon EMAs spread and ordered (5>8>13>21 for BUY). Enter on first candle that touches EMA5 as pullback.',
    exitLogic: 'Exit at first ribbon compression (EMAs converging) or 1.6×ATR profit.',
    tags: ['scalp', 'ribbon', 'momentum'],
  },
  {
    name: 'MOMENTUM_SCALP',
    displayName: 'Momentum Burst Scalp',
    description: 'Captures explosive momentum bursts using volume + RSI divergence from VWAP. Platinum-only precision.',
    category: 'SCALPING',
    tier: 'PLATINUM',
    assetClasses: ['CRYPTO', 'STOCK'],
    bestTimeframes: ['1m', '5m'],
    indicatorWeights: [
      { indicator: 'VWAP', weight: 2.5, required: true },
      { indicator: 'Volume', weight: 2.0, required: true },
      { indicator: 'RSI(14)', weight: 1.5 },
      { indicator: 'OBV', weight: 1.5 },
      { indicator: 'MACD', weight: 1.0 },
    ],
    riskParams: { atrMultiplierSL: 0.5, atrMultiplierTP: 1.2, minRR: 2.0, positionSizeFraction: 0.02 },
    signalThreshold: 0.45,
    requiresFundamental: false,
    fundamentalWeight: 0.05,
    entryLogic: 'Price aggressively moves away from VWAP on 5× volume surge. RSI momentum confirms. Enter in direction of VWAP deviation.',
    exitLogic: 'Exit at VWAP reversion or 1.2×ATR. Tight 0.5×ATR stop. High frequency — 5-10 minutes max.',
    tags: ['vwap', 'ultra-fast', 'institutional-flow', 'platinum'],
  },
];
