import { StrategyDefinition } from './strategy.interface';

export const TREND_STRATEGIES: StrategyDefinition[] = [
  {
    name: 'EMA_CROSS',
    displayName: 'EMA Crossover',
    description: 'Classic 12/26 EMA crossover momentum strategy. Enters on golden/death cross with volume confirmation.',
    category: 'TREND',
    tier: 'SILVER',
    assetClasses: ['CRYPTO', 'FOREX', 'STOCK', 'COMMODITY'],
    bestTimeframes: ['1h', '4h', '1d'],
    indicatorWeights: [
      { indicator: 'EMA(12/26) Cross', weight: 2.0, required: true },
      { indicator: 'MACD', weight: 1.5 },
      { indicator: 'RSI(14)', weight: 0.8 },
      { indicator: 'Volume', weight: 1.2 },
    ],
    riskParams: { atrMultiplierSL: 1.5, atrMultiplierTP: 3.0, minRR: 2.0 },
    entryLogic: 'EMA12 crosses above/below EMA26 with MACD histogram momentum confirmation and above-average volume.',
    exitLogic: 'Exit when EMA12 reverses cross or price closes beyond 1.5×ATR stop.',
    tags: ['momentum', 'crossover', 'beginner-friendly'],
  },
  {
    name: 'MACD_TREND',
    displayName: 'MACD Momentum',
    description: 'MACD histogram expansion with ADX trend strength filter. Only trades strong directional moves.',
    category: 'TREND',
    tier: 'SILVER',
    assetClasses: ['CRYPTO', 'FOREX', 'STOCK'],
    bestTimeframes: ['1h', '4h'],
    indicatorWeights: [
      { indicator: 'MACD', weight: 2.0, required: true },
      { indicator: 'ADX', weight: 1.8, required: true },
      { indicator: 'EMA(12/26) Cross', weight: 1.0 },
      { indicator: 'RSI(14)', weight: 0.6 },
    ],
    riskParams: { atrMultiplierSL: 1.8, atrMultiplierTP: 3.5, minRR: 1.8 },
    entryLogic: 'MACD line crosses signal line with histogram expanding; ADX > 20 confirms trend strength.',
    exitLogic: 'MACD histogram contracts to 50% peak or ADX drops below 20.',
    tags: ['momentum', 'trend-strength', 'adx-filtered'],
  },
  {
    name: 'ADX_TREND_FOLLOW',
    displayName: 'ADX Trend Follower',
    description: 'Pure trend-following using ADX 25+ filter with +DI/-DI directional signals.',
    category: 'TREND',
    tier: 'SILVER',
    assetClasses: ['FOREX', 'COMMODITY', 'CRYPTO'],
    bestTimeframes: ['4h', '1d'],
    indicatorWeights: [
      { indicator: 'ADX', weight: 2.5, required: true },
      { indicator: 'MACD', weight: 1.2 },
      { indicator: 'EMA(50)', weight: 1.0 },
      { indicator: 'RSI(14)', weight: 0.5 },
    ],
    riskParams: { atrMultiplierSL: 2.0, atrMultiplierTP: 4.0, minRR: 2.0 },
    signalThreshold: 0.30,
    entryLogic: 'ADX > 25 with +DI crossover (BUY) or -DI crossover (SELL). Price above/below EMA50 for trend bias.',
    exitLogic: 'ADX falls below 20 or price reverses through EMA50.',
    tags: ['trend-strength', 'directional', 'swing'],
  },
  {
    name: 'SUPERTREND_FOLLOW',
    displayName: 'Supertrend',
    description: 'ATR-based Supertrend indicator for dynamic trend following with built-in stop adjustment.',
    category: 'TREND',
    tier: 'GOLD',
    assetClasses: ['CRYPTO', 'FOREX', 'STOCK', 'COMMODITY'],
    bestTimeframes: ['15m', '1h', '4h'],
    indicatorWeights: [
      { indicator: 'Supertrend', weight: 2.5, required: true },
      { indicator: 'EMA(50)', weight: 1.0 },
      { indicator: 'RSI(14)', weight: 0.7 },
      { indicator: 'Volume', weight: 0.8 },
    ],
    riskParams: { atrMultiplierSL: 1.0, atrMultiplierTP: 3.0, minRR: 2.5, positionSizeFraction: 0.06 },
    entryLogic: 'Enter when price crosses above (BUY) or below (SELL) Supertrend line. EMA50 must agree with direction.',
    exitLogic: 'Exit when price closes on opposite side of Supertrend line.',
    tags: ['dynamic-stop', 'atr-based', 'adaptive'],
  },
  {
    name: 'TRIPLE_EMA',
    displayName: 'Triple EMA Cascade',
    description: 'Requires alignment of EMA8, EMA21, and EMA55 in cascade formation for high-confidence trend entries.',
    category: 'TREND',
    tier: 'GOLD',
    assetClasses: ['CRYPTO', 'STOCK', 'FOREX'],
    bestTimeframes: ['1h', '4h', '1d'],
    indicatorWeights: [
      { indicator: 'EMA(8)', weight: 1.5, required: true },
      { indicator: 'EMA(21)', weight: 1.5, required: true },
      { indicator: 'EMA(55)', weight: 1.5, required: true },
      { indicator: 'MACD', weight: 1.0 },
      { indicator: 'Volume', weight: 1.2 },
    ],
    riskParams: { atrMultiplierSL: 1.8, atrMultiplierTP: 4.0, minRR: 2.0, positionSizeFraction: 0.07 },
    signalThreshold: 0.35,
    entryLogic: 'All three EMAs must be in cascade order (8>21>55 for BUY, 8<21<55 for SELL) with MACD momentum.',
    exitLogic: 'Exit when EMA8 crosses back through EMA21.',
    tags: ['cascade', 'high-confidence', 'multiple-confirmation'],
  },
];
