export type TierName = 'NONE' | 'DEFAULT' | 'SILVER' | 'GOLD' | 'PLATINUM';

export const TIER_CONFIG = {
  NONE: {
    depositRequired: 0,
    monthlyFee: 0,
    canTrade: false,
    canTradeCrypto: false,
    maxPositions: 0,
    maxLeverage: 1,
    maxAssets: 0,
    commission: 0.001,
    allowedAssetCategories: [] as string[],
    allowedCryptoSymbols: [] as string[],
    allowedForexSymbols: [] as string[],
    allowedStockSymbols: [] as string[],
    indicators: [] as string[],
    orderTypes: [] as string[],
    botAccess: 'none' as 'none' | 'signals' | 'full' | 'premium',
    backtestLimit: 0,
    label: 'No Plan',
    color: '#5d6673',
  },
  DEFAULT: {
    depositRequired: 250,
    monthlyFee: 0,
    canTrade: true,
    canTradeCrypto: false,
    maxPositions: 3,
    maxLeverage: 3,
    maxAssets: 8,
    commission: 0.001,
    allowedAssetCategories: ['FOREX', 'CRYPTO'], // crypto is view-only
    allowedCryptoSymbols: ['BTCUSD'], // view-only
    allowedForexSymbols: ['EURUSD','GBPUSD','USDJPY','USDCHF','AUDUSD','USDCAD','NZDUSD'],
    allowedStockSymbols: [] as string[],
    indicators: ['SMA','EMA','RSI'],
    orderTypes: ['MARKET','LIMIT'],
    botAccess: 'none' as const,
    backtestLimit: 0,
    label: 'Default',
    color: '#64748b',
  },
  SILVER: {
    depositRequired: 2500,
    monthlyFee: 29,
    canTrade: true,
    canTradeCrypto: true,
    maxPositions: 5,
    maxLeverage: 5,
    maxAssets: 20,
    commission: 0.001,
    allowedAssetCategories: ['FOREX', 'CRYPTO'],
    allowedCryptoSymbols: ['BTCUSD','ETHUSD','SOLUSD','XRPUSD','BNBUSD','ADAUSD','DOGEUSD','AVAXUSD','DOTUSD','MATICUSD'],
    allowedForexSymbols: 'ALL_MAJORS' as const,
    allowedStockSymbols: [] as string[],
    indicators: ['SMA','EMA','RSI','MACD','BB'],
    orderTypes: ['MARKET','LIMIT','STOP_LOSS'],
    botAccess: 'signals' as const,
    backtestLimit: 0,
    label: 'Silver',
    color: '#94a3b8',
  },
  GOLD: {
    depositRequired: 10000,
    monthlyFee: 199,
    canTrade: true,
    canTradeCrypto: true,
    maxPositions: 20,
    maxLeverage: 20,
    maxAssets: 80,
    commission: 0.0005,
    allowedAssetCategories: ['FOREX', 'CRYPTO', 'STOCKS'],
    allowedCryptoSymbols: 'TOP_50' as const,
    allowedForexSymbols: 'ALL' as const,
    allowedStockSymbols: ['AAPL','TSLA','NVDA','GOOGL','MSFT','AMZN','META','NFLX','AMD','INTC','JPM','V','MA','DIS','PYPL','UBER','COIN','SQ','BABA','NIO'],
    indicators: 'ALL' as const,
    orderTypes: ['MARKET','LIMIT','STOP_LOSS','TAKE_PROFIT'],
    botAccess: 'full' as const,
    backtestLimit: 50,
    label: 'Gold',
    color: '#f59e0b',
  },
  PLATINUM: {
    depositRequired: 50000,
    monthlyFee: 499,
    canTrade: true,
    canTradeCrypto: true,
    maxPositions: 999,
    maxLeverage: 100,
    maxAssets: 999,
    commission: 0.0001,
    allowedAssetCategories: ['FOREX', 'CRYPTO', 'STOCKS', 'COMMODITIES', 'INDICES', 'FUTURES'],
    allowedCryptoSymbols: 'ALL' as const,
    allowedForexSymbols: 'ALL' as const,
    allowedStockSymbols: 'ALL' as const,
    indicators: 'ALL' as const,
    orderTypes: ['MARKET','LIMIT','STOP_LOSS','TAKE_PROFIT','OCO'],
    botAccess: 'premium' as const,
    backtestLimit: 999,
    label: 'Platinum',
    color: '#a78bfa',
  },
} as const;

export function getTierConfig(tier: TierName) {
  return TIER_CONFIG[tier] ?? TIER_CONFIG.NONE;
}

// Map User.plan string to TierName
export function planStringToTier(plan: string | undefined): TierName {
  const map: Record<string, TierName> = {
    none: 'NONE',
    default: 'DEFAULT',
    silver: 'SILVER',
    gold: 'GOLD',
    platinum: 'PLATINUM',
  };
  return map[plan?.toLowerCase() ?? 'none'] ?? 'NONE';
}
